import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('vehicle_makes').insert([
      {
        title: 'Acura',
        slug: 'acura',
        description: 'Acura',
        created_at: new Date(),
      },
      {
        title: 'Alfa Romeo',
        slug: 'alfa-romeo',
        description: 'Alfa Romeo',
        created_at: new Date(),
      },
      {
        title: 'AM General',
        slug: 'am-general',
        description: 'AM General',
        created_at: new Date(),
      },
      {
        title: 'Aston Martin',
        slug: 'aston-martin',
        description: 'Aston Martin',
        created_at: new Date(),
      },
      {
        title: 'Audi',
        slug: 'audi',
        description: 'Audi',
        created_at: new Date(),
      },
      {
        title: 'Bentley',
        slug: 'bentley',
        description: 'Bentley',
        created_at: new Date(),
      },
      {
        title: 'BMW',
        slug: 'bmw',
        description: 'BMW',
        created_at: new Date(),
      },
      {
        title: 'Bugatti',
        slug: 'bugatti',
        description: 'Bugatti',
        created_at: new Date(),
      },
      {
        title: 'Buick',
        slug: 'buick',
        description: 'Buick',
        created_at: new Date(),
      },
      {
        title: 'Cadillac',
        slug: 'cadillac',
        description: 'Cadillac',
        created_at: new Date(),
      },
      {
        title: 'Chevrolet',
        slug: 'chevrolet',
        description: 'Chevrolet',
        created_at: new Date(),
      },
      {
        title: 'Chrysler',
        slug: 'chrysler',
        description: 'Chrysler',
        created_at: new Date(),
      },
      {
        title: 'Daewoo',
        slug: 'daewoo',
        description: 'Daewoo',
        created_at: new Date(),
      },
      {
        title: 'Dodge',
        slug: 'dodge',
        description: 'Dodge',
        created_at: new Date(),
      },
      {
        title: 'Eagle',
        slug: 'eagle',
        description: 'Eagle',
        created_at: new Date(),
      },
      {
        title: 'Ferrari',
        slug: 'ferrari',
        description: 'Ferrari',
        created_at: new Date(),
      },
      {
        title: 'FIAT',
        slug: 'fiat',
        description: 'FIAT',
        created_at: new Date(),
      },
      {
        title: 'Fisker',
        slug: 'fisker',
        description: 'Fisker',
        created_at: new Date(),
      },
      {
        title: 'Ford',
        slug: 'ford',
        description: 'Ford',
        created_at: new Date(),
      },
      {
        title: 'Genesis',
        slug: 'genesis',
        description: 'Genesis',
        created_at: new Date(),
      },
      {
        title: 'Geo',
        slug: 'geo',
        description: 'Geo',
        created_at: new Date(),
      },
      {
        title: 'GMC',
        slug: 'gmc',
        description: 'GMC',
        created_at: new Date(),
      },
      {
        title: 'Honda',
        slug: 'honda',
        description: 'Honda',
        created_at: new Date(),
      },
      {
        title: 'HUMMER',
        slug: 'hummer',
        description: 'HUMMER',
        created_at: new Date(),
      },
      {
        title: 'Hyundai',
        slug: 'hyundai',
        description: 'Hyundai',
        created_at: new Date(),
      },
      {
        title: 'INEOS',
        slug: 'ineos',
        description: 'INEOS',
        created_at: new Date(),
      },
      {
        title: 'INFINITI',
        slug: 'infiniti',
        description: 'INFINITI',
        created_at: new Date(),
      },
      {
        title: 'Isuzu',
        slug: 'isuzu',
        description: 'Isuzu',
        created_at: new Date(),
      },
      {
        title: 'Jaguar',
        slug: 'jaguar',
        description: 'Jaguar',
        created_at: new Date(),
      },
      {
        title: 'Jeep',
        slug: 'jeep',
        description: 'Jeep',
        created_at: new Date(),
      },
      {
        title: 'Karma',
        slug: 'karma',
        description: 'Karma',
        created_at: new Date(),
      },
      {
        title: 'Kia',
        slug: 'kia',
        description: 'Kia',
        created_at: new Date(),
      },
      {
        title: 'Lamborghini',
        slug: 'lamborghini',
        description: 'Lamborghini',
        created_at: new Date(),
      },
      {
        title: 'Land Rover',
        slug: 'land-rover',
        description: 'Land Rover',
        created_at: new Date(),
      },
      {
        title: 'Lexus',
        slug: 'lexus',
        description: 'Lexus',
        created_at: new Date(),
      },
      {
        title: 'Lincoln',
        slug: 'lincoln',
        description: 'Lincoln',
        created_at: new Date(),
      },
      {
        title: 'Lucid',
        slug: 'lucid',
        description: 'Lucid',
        created_at: new Date(),
      },
      {
        title: 'Maserati',
        slug: 'maserati',
        description: 'Maserati',
        created_at: new Date(),
      },
      {
        title: 'Maybach',
        slug: 'maybach',
        description: 'Maybach',
        created_at: new Date(),
      },
      {
        title: 'Mazda',
        slug: 'mazda',
        description: 'Mazda',
        created_at: new Date(),
      },
      {
        title: 'McLaren',
        slug: 'mclaren',
        description: 'McLaren',
        created_at: new Date(),
      },
      {
        title: 'Mercedes-Benz',
        slug: 'mercedes-benz',
        description: 'Mercedes-Benz',
        created_at: new Date(),
      },
      {
        title: 'Mercury',
        slug: 'mercury',
        description: 'Mercury',
        created_at: new Date(),
      },
      {
        title: 'MINI',
        slug: 'mini',
        description: 'MINI',
        created_at: new Date(),
      },
      {
        title: 'Mitsubishi',
        slug: 'mitsubishi',
        description: 'Mitsubishi',
        created_at: new Date(),
      },
      {
        title: 'Nissan',
        slug: 'nissan',
        description: 'Nissan',
        created_at: new Date(),
      },
      {
        title: 'Oldsmobile',
        slug: 'oldsmobile',
        description: 'Oldsmobile',
        created_at: new Date(),
      },
      {
        title: 'Panoz',
        slug: 'panoz',
        description: 'Panoz',
        created_at: new Date(),
      },
      {
        title: 'Plymouth',
        slug: 'plymouth',
        description: 'Plymouth',
        created_at: new Date(),
      },
      {
        title: 'Pontiac',
        slug: 'pontiac',
        description: 'Pontiac',
        created_at: new Date(),
      },
      {
        title: 'Polestar',
        slug: 'polestar',
        description: 'Polestar',
        created_at: new Date(),
      },
      {
        title: 'Porsche',
        slug: 'porsche',
        description: 'Porsche',
        created_at: new Date(),
      },
      {
        title: 'Ram',
        slug: 'ram',
        description: 'Ram',
        created_at: new Date(),
      },
      {
        title: 'Rivian',
        slug: 'rivian',
        description: 'Rivian',
        created_at: new Date(),
      },
      {
        title: 'Rolls-Royce',
        slug: 'rolls-royce',
        description: 'Rolls-Royce',
        created_at: new Date(),
      },
      {
        title: 'Saab',
        slug: 'saab',
        description: 'Saab',
        created_at: new Date(),
      },
      {
        title: 'Saturn',
        slug: 'saturn',
        description: 'Saturn',
        created_at: new Date(),
      },
      {
        title: 'Scion',
        slug: 'scion',
        description: 'Scion',
        created_at: new Date(),
      },
      {
        title: 'Smart',
        slug: 'smart',
        description: 'Smart',
        created_at: new Date(),
      },
      {
        title: 'Spyker',
        slug: 'spyker',
        description: 'Spyker',
        created_at: new Date(),
      },
      {
        title: 'Subaru',
        slug: 'subaru',
        description: 'Subaru',
        created_at: new Date(),
      },
      {
        title: 'Suzuki',
        slug: 'suzuki',
        description: 'Suzuki',
        created_at: new Date(),
      },
      {
        title: 'Tesla',
        slug: 'Tesla',
        description: 'Tesla',
        created_at: new Date(),
      },
      {
        title: 'Toyota',
        slug: 'toyota',
        description: 'Toyota',
        created_at: new Date(),
      },
      {
        title: 'VinFast',
        slug: 'vinfast',
        description: 'VinFast',
        created_at: new Date(),
      },
      {
        title: 'Volkswagen',
        slug: 'volkswagen',
        description: 'Volkswagen',
        created_at: new Date(),
      },
      {
        title: 'Volvo',
        slug: 'volvo',
        description: 'Volvo',
        created_at: new Date(),
      }
    ])
  }
}
