import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('vehicle_makes').insert([
      { id: 1, title: 'Acura', slug: 'acura', description: 'Acura', created_at: new Date() },
      { id: 2, title: 'Alfa Romeo', slug: 'alfa-romeo', description: 'Alfa Romeo', created_at: new Date() },
      { id: 3, title: 'AM General', slug: 'am-general', description: 'AM General', created_at: new Date() },
      { id: 4, title: 'Aston Martin', slug: 'aston-martin', description: 'Aston Martin', created_at: new Date() },
      { id: 5, title: 'Audi', slug: 'audi', description: 'Audi', created_at: new Date() },
      { id: 6, title: 'Bentley', slug: 'bentley', description: 'Bentley', created_at: new Date() },
      { id: 7, title: 'Bugatti', slug: 'bugatti', description: 'Bugatti', created_at: new Date() },
      { id: 8, title: 'Buick', slug: 'buick', description: 'Buick', created_at: new Date() },
      { id: 9, title: 'Cadillac', slug: 'cadillac', description: 'Cadillac', created_at: new Date() },
      { id: 10, title: 'Chevrolet', slug: 'chevrolet', description: 'Chevrolet', created_at: new Date() },
      { id: 11, title: 'Chrysler', slug: 'chrysler', description: 'Chrysler', created_at: new Date() },
      { id: 12, title: 'Daewoo', slug: 'daewoo', description: 'Daewoo', created_at: new Date() },
      { id: 13, title: 'Dodge', slug: 'dodge', description: 'Dodge', created_at: new Date() },
      { id: 14, title: 'Eagle', slug: 'eagle', description: 'Eagle', created_at: new Date() },
      { id: 15, title: 'Ferrari', slug: 'ferrari', description: 'Ferrari', created_at: new Date() },
      { id: 16, title: 'FIAT', slug: 'fiat', description: 'FIAT', created_at: new Date() },
      { id: 17, title: 'Fisker', slug: 'fisker', description: 'Fisker', created_at: new Date() },
      { id: 18, title: 'Ford', slug: 'ford', description: 'Ford', created_at: new Date() },
      { id: 19, title: 'Genesis', slug: 'genesis', description: 'Genesis', created_at: new Date() },
      { id: 20, title: 'Geo', slug: 'geo', description: 'Geo', created_at: new Date() },
      { id: 21, title: 'GMC', slug: 'gmc', description: 'GMC', created_at: new Date() },
      { id: 22, title: 'Honda', slug: 'honda', description: 'Honda', created_at: new Date() },
      { id: 23, title: 'HUMMER', slug: 'hummer', description: 'HUMMER', created_at: new Date() },
      { id: 24, title: 'Hyundai', slug: 'hyundai', description: 'Hyundai', created_at: new Date() },
      { id: 25, title: 'INEOS', slug: 'ineos', description: 'INEOS', created_at: new Date() },
      { id: 26, title: 'INFINITI', slug: 'infiniti', description: 'INFINITI', created_at: new Date() },
      { id: 27, title: 'Isuzu', slug: 'isuzu', description: 'Isuzu', created_at: new Date() },
      { id: 28, title: 'Jaguar', slug: 'jaguar', description: 'Jaguar', created_at: new Date() },
      { id: 29, title: 'Jeep', slug: 'jeep', description: 'Jeep', created_at: new Date() },
      { id: 30, title: 'Karma', slug: 'karma', description: 'Karma', created_at: new Date() },
      { id: 31, title: 'Kia', slug: 'kia', description: 'Kia', created_at: new Date() },
      { id: 32, title: 'Lamborghini', slug: 'lamborghini', description: 'Lamborghini', created_at: new Date() },
      { id: 33, title: 'Land Rover', slug: 'land-rover', description: 'Land Rover', created_at: new Date() },
      { id: 34, title: 'Lexus', slug: 'lexus', description: 'Lexus', created_at: new Date() },
      { id: 35, title: 'Lincoln', slug: 'lincoln', description: 'Lincoln', created_at: new Date() },
      { id: 36, title: 'Lucid', slug: 'lucid', description: 'Lucid', created_at: new Date() },
      { id: 37, title: 'Maserati', slug: 'maserati', description: 'Maserati', created_at: new Date() },
      { id: 38, title: 'Maybach', slug: 'maybach', description: 'Maybach', created_at: new Date() },
      { id: 39, title: 'Mazda', slug: 'mazda', description: 'Mazda', created_at: new Date() },
      { id: 40, title: 'McLaren', slug: 'mclaren', description: 'McLaren', created_at: new Date() },
      { id: 41, title: 'Mercedes-Benz', slug: 'mercedes-benz', description: 'Mercedes-Benz', created_at: new Date() },
      { id: 42, title: 'Mercury', slug: 'mercury', description: 'Mercury', created_at: new Date() },
      { id: 43, title: 'MINI', slug: 'mini', description: 'MINI', created_at: new Date() },
      { id: 44, title: 'Mitsubishi', slug: 'mitsubishi', description: 'Mitsubishi', created_at: new Date() },
      { id: 45, title: 'Nissan', slug: 'nissan', description: 'Nissan', created_at: new Date() },
      { id: 46, title: 'Oldsmobile', slug: 'oldsmobile', description: 'Oldsmobile', created_at: new Date() },
      { id: 47, title: 'Panoz', slug: 'panoz', description: 'Panoz', created_at: new Date() },
      { id: 48, title: 'Plymouth', slug: 'plymouth', description: 'Plymouth', created_at: new Date() },
      { id: 49, title: 'Pontiac', slug: 'pontiac', description: 'Pontiac', created_at: new Date() },
      { id: 50, title: 'Polestar', slug: 'polestar', description: 'Polestar', created_at: new Date() },
      { id: 51, title: 'Porsche', slug: 'porsche', description: 'Porsche', created_at: new Date() },
      { id: 52, title: 'Ram', slug: 'ram', description: 'Ram', created_at: new Date() },
      { id: 53, title: 'Rivian', slug: 'rivian', description: 'Rivian', created_at: new Date() },
      { id: 54, title: 'Rolls-Royce', slug: 'rolls-royce', description: 'Rolls-Royce', created_at: new Date() },
      { id: 55, title: 'Saab', slug: 'saab', description: 'Saab', created_at: new Date() },
      { id: 56, title: 'Saturn', slug: 'saturn', description: 'Saturn', created_at: new Date() },
      { id: 57, title: 'Scion', slug: 'scion', description: 'Scion', created_at: new Date() },
      { id: 58, title: 'Smart', slug: 'smart', description: 'Smart', created_at: new Date() },
      { id: 59, title: 'Spyker', slug: 'spyker', description: 'Spyker', created_at: new Date() },
      { id: 60, title: 'Subaru', slug: 'subaru', description: 'Subaru', created_at: new Date() },
      { id: 61, title: 'Suzuki', slug: 'suzuki', description: 'Suzuki', created_at: new Date() },
      { id: 62, title: 'Tesla', slug: 'tesla', description: 'Tesla', created_at: new Date() },
      { id: 63, title: 'Toyota', slug: 'toyota', description: 'Toyota', created_at: new Date() },
      { id: 64, title: 'VinFast', slug: 'vinfast', description: 'VinFast', created_at: new Date() },
      { id: 65, title: 'Volkswagen', slug: 'volkswagen', description: 'Volkswagen', created_at: new Date() },
      { id: 66, title: 'Volvo', slug: 'volvo', description: 'Volvo', created_at: new Date() },
      { id: 67, title: 'BMW (Germany)', slug: 'bmw-germany', description: 'BMW (Germany)', created_at: new Date() },
    ])
  }
}
