import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('media').insert([
      {
        user_id: 3,
        slug: 'med_veh7_0',
        module: 'vehicle',
        module_id: 1,
        filename: 'mercedes_modified_1',
        original_name: 'mercedes_modified_1',
        file_url: 'vehicle/mercedes_modified_1.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_modified_1.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_1',
        module: 'vehicle',
        module_id: 1,
        filename: 'mercedes_modified_2',
        original_name: 'mercedes_modified_2',
        file_url: 'vehicle/mercedes_modified_2.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_modified_2.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_2',
        module: 'vehicle',
        module_id: 1,
        filename: 'mercedes_modified_3',
        original_name: 'mercedes_modified_3',
        file_url: 'vehicle/mercedes_modified_3.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_modified_3.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_3',
        module: 'vehicle',
        module_id: 2,
        filename: 'ford_mustang_1',
        original_name: 'ford_mustang_1',
        file_url: 'vehicle/ford_mustang_1.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_mustang_1.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_4',
        module: 'vehicle',
        module_id: 2,
        filename: 'ford_mustang_2',
        original_name: 'ford_mustang_2',
        file_url: 'vehicle/ford_mustang_2.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_mustang_2.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_5',
        module: 'vehicle',
        module_id:2,
        filename: 'ford_mustang_3',
        original_name: 'ford_mustang_3',
        file_url: 'vehicle/ford_mustang_3.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_mustang_3.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_6',
        module: 'vehicle',
        module_id: 3,
        filename: 'mercedes_track_1',
        original_name: 'mercedes_track_1',
        file_url: 'vehicle/mercedes_track_1.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_track_1.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_7',
        module: 'vehicle',
        module_id: 3,
        filename: 'mercedes_track_2',
        original_name: 'mercedes_track_2',
        file_url: 'vehicle/mercedes_track_2.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_track_2.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_8',
        module: 'vehicle',
        module_id: 3,
        filename: 'mercedes_track_3',
        original_name: 'mercedes_track_3',
        file_url: 'vehicle/mercedes_track_3.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_track_3.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_9',
        module: 'vehicle',
        module_id: 3,
        filename: 'mercedes_track_4',
        original_name: 'mercedes_track_4',
        file_url: 'vehicle/mercedes_track_4.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/mercedes_track_4.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_10',
        module: 'vehicle',
        module_id: 4,
        filename: 'ford_1',
        original_name: 'ford_1',
        file_url: 'vehicle/ford_1.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_1.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_11',
        module: 'vehicle',
        module_id: 4,
        filename: 'ford_2',
        original_name: 'ford_2',
        file_url: 'vehicle/ford_2.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_2.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_12',
        module: 'vehicle',
        module_id: 4,
        filename: 'ford_3',
        original_name: 'ford_3',
        file_url: 'vehicle/ford_3.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_3.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_13',
        module: 'vehicle',
        module_id: 4,
        filename: 'ford_4',
        original_name: 'ford_4',
        file_url: 'vehicle/ford_4.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_4.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_14',
        module: 'vehicle',
        module_id: 4,
        filename: 'ford_5',
        original_name: 'ford_5',
        file_url: 'vehicle/ford_5.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/ford_5.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_15',
        module: 'vehicle',
        module_id: 5,
        filename: 'bmw_1',
        original_name: 'bmw_1',
        file_url: 'vehicle/bmw_1.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/bmw_1.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_16',
        module: 'vehicle',
        module_id: 5,
        filename: 'bmw_2',
        original_name: 'bmw_2',
        file_url: 'vehicle/bmw_2.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/bmw_2.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_18',
        module: 'vehicle',
        module_id: 6,
        filename: 'toyota_1',
        original_name: 'toyota_1',
        file_url: 'vehicle/toyota_1.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/toyota_1.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_19',
        module: 'vehicle',
        module_id: 6,
        filename: 'toyota_2',
        original_name: 'toyota_2',
        file_url: 'vehicle/toyota_2.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/toyota_2.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
      {
        user_id: 3,
        slug: 'med_veh7_20',
        module: 'vehicle',
        module_id: 6,
        filename: 'toyota_3',
        original_name: 'toyota_3',
        file_url: 'vehicle/toyota_3.jpg',
        file_url_blur: '0000',
        thumbnail_url: 'vehicle/toyota_3.jpg',
        mime_type: 'image/jpeg',
        file_type: 'image',
        driver: 'local',
        media_type: 'public',
        meta: '',
        created_at: new Date(),
      },
    ])
  }
}
