import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('cms_module_permissions').insert([
      {
        user_group_id: '2',
        cms_module_id: '1',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '6',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '7',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '8',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '9',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '11',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '15',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '16',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '17',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      // {
      //   user_group_id: '2',
      //   cms_module_id: '18',
      //   is_add: '1',
      //   is_view: '1',
      //   is_update: '1',
      //   is_delete: '1',
      //   created_at: new Date(),
      // },
      // {
      //   user_group_id: '2',
      //   cms_module_id: '19',
      //   is_add: '1',
      //   is_view: '1',
      //   is_update: '1',
      //   is_delete: '1',
      //   created_at: new Date(),
      // },
      // {
      //   user_group_id: '2',
      //   cms_module_id: '20',
      //   is_add: '1',
      //   is_view: '1',
      //   is_update: '1',
      //   is_delete: '1',
      //   created_at: new Date(),
      // },
      // {
      //   user_group_id: '2',
      //   cms_module_id: '20',
      //   is_add: '1',
      //   is_view: '1',
      //   is_update: '1',
      //   is_delete: '1',
      //   created_at: new Date(),
      // },
      {
        user_group_id: '2',
        cms_module_id: '21',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '28',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '30',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '32',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      },
      {
        user_group_id: '2',
        cms_module_id: '33',
        is_add: '1',
        is_view: '1',
        is_update: '1',
        is_delete: '1',
        created_at: new Date(),
      }
    ]);
  }
}
