import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('vehicles').insert([
      {
        slug: 'mercedes-modified',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 25,
        vehicle_mileage: '25000 miles',
        vehicle_price: '35000',
        vehicle_primarily_used: 'straight_line_racing',
        vehicle_title: '2008 Mercedes-Benz C63 AMG Sedan',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: '6.2-Liter V8, California-Owned, Some Modifications',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'#000000',
        interior_color:'#ffffff',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: 'ford-mustang',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 2,
        vehicle_model: 12,
        vehicle_year: 26,
        vehicle_mileage: '25000 miles',
        vehicle_price: '35000',
        vehicle_primarily_used: 'daily_driver',
        vehicle_title: '2021 Ford Mustang GT RTR Spec 5 Coupe',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Turbocharger Upgrade',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'#000000',
        interior_color:'#ffffff',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: 'mercedes-track',
        vehicle_category_id: 2,
        user_id: 3,
        vehicle_make: 3,
        vehicle_model: 18,
        vehicle_year: 25,
        vehicle_mileage: '25000 miles',
        vehicle_price: '35000',
        vehicle_primarily_used: 'daily_driver',
        vehicle_title: 'Mercedes - Track Ready',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Turbocharger Upgrade',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'#000000',
        interior_color:'#ffffff',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: '2014-ford-mustang',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 4,
        vehicle_model: 24,
        vehicle_year: 26,
        vehicle_mileage: '25000 miles',
        vehicle_price: '35000',
        vehicle_primarily_used: 'daily_driver',
        vehicle_title: '2006 Ford Mustang GT Coupe',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Miami',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'#000000',
        interior_color:'#ffffff',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: '2011-bmw-e92',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 4,
        vehicle_model: 23,
        vehicle_year: 25,
        vehicle_mileage: '35000 miles',
        vehicle_price: '25000',
        vehicle_primarily_used: 'drift_racing',
        vehicle_title: '2011 BMW E92 M3-Competition Package',
        vehicle_descripition: 'This stunning 2011 BMW GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Miami',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'#000000',
        interior_color:'#ffffff',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: '2019-toyota',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 5,
        vehicle_model: 30,
        vehicle_year: 23,
        vehicle_mileage: '85000 miles',
        vehicle_price: '35800',
        vehicle_primarily_used: 'mud_bogging',
        vehicle_title: '2019 Toyota 86-Widebody Show Car',
        vehicle_descripition: 'This stunning 2019 Corolla features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Rocket bunny kit',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'#000000',
        interior_color:'#ffffff',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        status: '1',
        created_at: new Date(),
      },
    ])
  }
}
