import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Database from '@ioc:Adonis/Lucid/Database'

export default class extends BaseSeeder {
  public async run () {
    await Database.table('vehicles').insert([
      {
        slug: 'mercedes-modified',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 25,
        vehicle_mileage: '25000',
        vehicle_price: '35000',
        vehicle_primarily_used: 'straight_line_racing',
        vehicle_title: '2008 Mercedes-Benz C63 AMG Sedan',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: '6.2-Liter V8, California-Owned, Some Modifications',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'black',
        interior_color:'white',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        country:'USA',
        postal_code:'87501',
        formatted_address:'Santa Fe Lane, residential, Socorro, United States',
        latitude:'34.075959',
        longitude:'-106.886113',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: 'ford-mustang',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 26,
        vehicle_mileage: '25000',
        vehicle_price: '35000',
        vehicle_primarily_used: 'daily_driver',
        vehicle_title: '2021 Ford Mustang GT RTR Spec 5 Coupe',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Turbocharger Upgrade',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'blue',
        interior_color:'black',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        country:'USA',
        postal_code:'90095',
        formatted_address:'University of California, Los Angeles, university, Los Angeles, United States',
        latitude:'34.070877749999994',
        longitude:'-118.44685031405575',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: 'mercedes-track',
        vehicle_category_id: 2,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 25,
        vehicle_mileage: '25000',
        vehicle_price: '35000',
        vehicle_primarily_used: 'daily_driver',
        vehicle_title: 'Mercedes - Track Ready',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Turbocharger Upgrade',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'red',
        interior_color:'blue',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        country:'USA',
        postal_code:'6161',
        formatted_address:'Fox Studios, studio, Los Angeles, United States',
        latitude:'34.05201125',
        longitude:'-118.41251178908388',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: '2014-ford-mustang',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 26,
        vehicle_mileage: '25000',
        vehicle_price: '35000',
        vehicle_primarily_used: 'daily_driver',
        vehicle_title: '2006 Ford Mustang GT Coupe',
        vehicle_descripition: 'This stunning 2022 Ford Mustang GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Miami',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'black',
        interior_color:'red',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        country:'USA',
        postal_code:'91234',
        formatted_address:'Ebell of Los Angeles, yes, Los Angeles, United States',
        latitude:'34.06114455',
        longitude:'-118.3249702734384',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: '2011-bmw-e92',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 25,
        vehicle_mileage: '35000',
        vehicle_price: '25000',
        vehicle_primarily_used: 'drift_racing',
        vehicle_title: '2011 BMW E92 M3-Competition Package',
        vehicle_descripition: 'This stunning 2011 BMW GT features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Miami',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'green',
        interior_color:'yellow',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        country:'USA',
        postal_code:'91234',
        formatted_address:'Hyatt Place LAX / Century Blvd, hotel, Los Angeles, United States',
        latitude:'33.94630235',
        longitude:'-118.38823905000001',
        status: '1',
        created_at: new Date(),
      },
      {
        slug: '2019-toyota',
        vehicle_category_id: 1,
        user_id: 3,
        vehicle_make: 1,
        vehicle_model: 6,
        vehicle_year: 23,
        vehicle_mileage: '85000',
        vehicle_price: '35800',
        vehicle_primarily_used: 'mud_bogging',
        vehicle_title: '2019 Toyota 86-Widebody Show Car',
        vehicle_descripition: 'This stunning 2019 Corolla features a powerful turbocharger upgrade, a performance suspension kit for improved handling, and a custom exhaust system that provides an aggressive sound. Low mileage and well-maintained.',
        vehicle_modification: 'Rocket bunny kit',
        driver_type:1,
        motor_size_cylinders:2,
        transmition_types:2,
        fuel_types:3,
        number_of_doors:4,
        exterior_color:'white',
        interior_color:'red',
        seller_type:1,
        vehicle_status:4,
        suspension_size:12,
        suspension_type:3,
        chassis_reinforcement:'0',
        chassis_reinforcement_text:'',
        audio_upgrade:'0',
        audio_upgrade_text:'',
        wheel_width:15,
        wheel_diameter:12,
        hp_output_rang:3,
        cosmetic_upgrade:'0',
        cosmetic_upgrade_text:'',
        vehicle_use:4,
        interior_upgrade:'0',
        interior_upgrade_text:'',
        exterior_upgrade:'0',
        exterior_upgrade_text:'',
        motor_upgrade:'0',
        motor_upgrade_text:'',
        documentation_type:2,
        vehicle_owner_name: 'Herry',
        vehicle_owner_address: 'Los Angeles, CA',
        vehicle_owner_email: 'herry@yopmail.com',
        vehicle_owner_phone: '1231231234',
        country:'USA',
        postal_code:'91234',
        formatted_address:'Van Nuys Airport, aerodrome, Los Angeles, United States',
        latitude:'34.2072085',
        longitude:'-118.49014800288717',
        status: '1',
        created_at: new Date(),
      },
    ])
  }
}
